# Generated by Django 2.0.2 on 2018-03-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muxic', '0004_auto_20180315_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
